version: '3'
services:
  dyoj-backend-gateway:
    container_name: dyoj-backend-gateway
    build:
      context: ./dyoj-backend-gateway
      dockerfile: Dockerfile
    ports:
      - "8104:8104"
    networks:
      - dyOjNetwork

  dyoj-backend-user-service:
    container_name: dyoj-backend-user-service
    build:
      context: ./dyoj-backend-user-service
      dockerfile: Dockerfile
    ports:
      - "8102:8102"
    networks:
      - dyOjNetwork
    depends_on:
      - dyoj-backend-gateway

  dyoj-backend-question-service:
    container_name: dyoj-backend-question-service
    build:
      context: ./dyoj-backend-question-service
      dockerfile: Dockerfile
    ports:
      - "8103:8103"
    networks:
      - dyOjNetwork
    depends_on:
      - dyoj-backend-user-service
      - dyoj-backend-gateway

  dyoj-backend-judge-service:
    container_name: dyoj-backend-judge-service
    build:
      context: ./dyoj-backend-judge-service
      dockerfile: Dockerfile
    ports:
      - "8105:8105"
    networks:
      - dyOjNetwork
    depends_on:
      - dyoj-backend-user-service
      - dyoj-backend-question-service
      - dyoj-backend-gateway

# 网络，不定义的话就是默认网络
networks:
  dyOjNetwork:
