version: '3'
services:
  mysql:
    image: mysql:8 # 使用的镜像
    container_name: dyoj-mysql # 启动的实例名称
    environment:
      MYSQL_ROOT_PASSWORD: dingyu@. # root 用户密码
    ports:
      - "3306:3306" # 端口映射
    volumes:
      - ./.mysql-data:/var/lib/mysql # 将数据目录挂载到本地目录以进行持久化
      - ./mysql-init:/docker-entrypoint-initdb.d # 启动脚本
    restart: always # 崩溃后自动重启
    networks:
      - dyOjNetwork # 指定网络
  redis:
    image: redis:6
    container_name: dyoj-redis
    ports:
      - "6379:6379"
    networks:
      - dyOjNetwork
    volumes:
      - ./.redis-data:/data # 持久化存储
    environment:
      REDIS_PASSWORD: dingyu@.      # 设置自定义密码
      REDIS_DATABASE: 1             # 设置 Redis 使用的数据库
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--databases", "16", "--dbfilename", "dump.rdb", "--dir", "/data", "--appendonly", "yes" ]
  rabbitmq:
    image: rabbitmq:3.12.6-management
    container_name: dyoj-rabbitmq
    environment:
      RABBITMQ_DEFAULT_VHOST: /dyoj      # 设置虚拟主机
      RABBITMQ_DEFAULT_USER: dyoj        # 设置自定义用户名
      RABBITMQ_DEFAULT_PASS: dingyu      # 设置自定义密码
    ports:
      - "5672:5672"      # RabbitMQ 服务端口
      - "15672:15672"    # RabbitMQ 管理面板端口
    volumes:
      - ./.rabbitmq-data:/var/lib/rabbitmq # 持久化存储
    networks:
      - dyOjNetwork

  nacos:
    image: nacos/nacos-server:v2.2.0-slim
    container_name: dyoj-nacos
    ports:
      - "8848:8848"
    volumes:
      - ./.nacos-data:/home/nacos/data
    networks:
      - dyOjNetwork
    environment:
      - MODE=standalone # 单节点模式启动
      - PREFER_HOST_MODE=hostname # 支持 hostname
      - TZ=Asia/Shanghai # 控制时区
networks:
  dyOjNetwork: