# 公共配置文件
 
spring:
  application:
    name: dyoj-backend-judge-service
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dy_oj
    username: root
    password: dingyu
  # Redis 配置
  redis:
    database: 1
    host: 8.130.9.216
    port: 6379
    timeout: 5000
    password: dingyu@.
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: 8.130.9.216:8848
  rabbitmq:
    host: 8.130.9.216 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /dyoj # 虚拟主机
    username: dyoj # 用户名
    password: dingyu # 密码
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初识的失败等待时长为1秒
          multiplier: 1 # 失败的等待时长倍数，下次等待时长 = multiplier * last-interval
          max-attempts: 6 # 最大重试次数
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
server:
  address: 0.0.0.0
  port: 8105
  servlet:
    context-path: /api/judge
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        path: /api
        secure: true
        same-site: none
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 代码沙箱配置
codeSandBox:
  type: example
knife4j:
  enable: true