
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/dy_oj
    username: root
    password: dingyu@.
  # Redis 配置
  redis:
    database: 1
    host: redis
    port: 6379
    timeout: 5000
    password: dingyu@.
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848

